# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jj3Zi3j4Vk9ZsyKmoZbNbBpVWy-G3aO_
"""

def hisoblash():
    print("Hisoblash dasturiga xush kelibsiz!")
    print("Quyidagi amallardan birini tanlang:")
    print("1. Qo'shish (+)")
    print("2. Ayirish (-)")
    print("3. Ko'paytirish (*)")
    print("4. Bo'lish (/)")


    amal = input("Amalni tanlang (1/2/3/4): ")

    if amal not in ['1', '2', '3', '4']:
        print("Noto'g'ri tanlov. Iltimos, qaytadan urinib ko'ring.")
        return

    try:
        son1 = float(input("Birinchi sonni kiriting: "))
        son2 = float(input("Ikkinchi sonni kiriting: "))
    except ValueError:
        print("Iltimos, to'g'ri son kiriting.")
        return

    if amal == '1':
        natija = son1 + son2
        print(f"Natija: {son1} + {son2} = {natija}")
    elif amal == '2':
        natija = son1 - son2
        print(f"Natija: {son1} - {son2} = {natija}")
    elif amal == '3':
        natija = son1 * son2
        print(f"Natija: {son1} * {son2} = {natija}")
    elif amal == '4':
        if son2 == 0:
            print("Nolga bo'lish mumkin emas!")
        else:
            natija = son1 / son2
            print(f"Natija: {son1} / {son2} = {natija}")

hisoblash()